- name: "Get playbook variables"
  include_vars:
    dir: 'vars'
    extensions: ['yml']


- name: Deploy new VM instance
    ec2:
     key_name: "{{ my_key_name }}"
     instance_type: "{{ instance_types[instance_type] }}"
     image: "{{ images[image] }}"
     wait: yes
     count: 1
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: yes
     group_id: "{{ group_id }}"
     region: "{{ region }}"
     instance_tags:
       app: "{{  app_name }}"