---
- hosts: localhost #ansible-tower
  connection: local

  tasks:
    - name: Job Template to launch a Workflow Job Template (as a workaround, waiting for CloudForms 4.5)
      uri:
        url: https://localhost/api/v1/workflow_job_templates/9/launch/
        method: POST
        body:
          extra_vars: "launched_from: CloudForms Mijo\nuser: admin\npassword: r3dh4t1!"
        body_format: json
        validate_certs: False
        headers_Content-Type: "application/json"
        status_code: 200, 201
  
  #vars:
  #  ansible_tower_ip: "{{ ansible_tower_ip }}"

  #roles:
  #- workflow_launcher