---
- name: Launching Workflow
  hosts: localhost
  gather_facts: False
  connection: local

  - name: Job Template to launch a Workflow Job Template
    uri:
      url: https://{{ ansible_tower_ip }}/api/v1/workflow_job_templates/{{ workflow_job_template_id }}/launch/
      method: POST
      user: "{{ tower_user }}"
      password: "{{ tower_pass }}"
      body:
        extra_vars:
          launched_from: CloudForms
      body_format: json
      validate_certs: False
      headers:
      Content-Type: "application/json"
      status_code: 200, 201
  
  
  #vars:
  #  ansible_tower_ip: "{{ ansible_tower_ip }}"

  #roles:
  #- workflow_launcher